/**
 * Partner profile picklists (aligned with UAE-heavy partner base).
 * Industry uses the same catalog as {@link LEAD_INDUSTRY_OPTIONS}.
 */
export { LEAD_INDUSTRY_OPTIONS as PARTNER_INDUSTRY_OPTIONS } from "./lead-detail-field-options"

export const NATIONALITY_OPTIONS = [
  "United Arab Emirates",
  "India",
  "Pakistan",
  "Egypt",
  "Jordan",
  "Lebanon",
  "Syria",
  "Palestine",
  "Iraq",
  "Yemen",
  "Oman",
  "Kuwait",
  "Bahrain",
  "Qatar",
  "Saudi Arabia",
  "United Kingdom",
  "United States",
  "Canada",
  "Australia",
  "New Zealand",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Ireland",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Philippines",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "China",
  "Japan",
  "South Korea",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Turkey",
  "Iran",
  "Russia",
  "Ukraine",
  "Poland",
  "Romania",
  "Brazil",
  "Mexico",
  "Other",
] as const
